### ISSUE TITLE
📖Documentation: Need help writing How-To-Use.md

### ISSUE THREAD

**Issue by N3v1** [N3v1/To-Do-App#3]
# Need help writing How-To-Use.md
**Hi everyone 👋**,
I might need some help. You could revise the [**How-To-Use.md file**](https://github.com/N3v1/To-Do-App/blob/main/How-To-Use.md) and add content if you want.

## Helpful Resources:
- https://www.markdownguide.org/cheat-sheet/

## Inspiration:
- [**README.md from this repo**](https://github.com/N3v1/To-Do-App/blob/main/README.md)

### Required Skills
- Basic/Advanced Markdown knowledge
- Basic/Advanced HTML knowledge

### Important Notes
**⚠️ Please sync your forks to prevent merge conflicts ⚠️**

### Requirements for the How-To-Use.md
**The How-To-Use.md file is intended to help the user understand how the app works:**
1. It should contain a small text about the functions of the app
2. Then a table of contents should be created. Here is a template:
```md
### Table of Contents
1. [Minimum Requirements](https://github.com/N3v1/To-Do-App#minimum-requirements)
2. [Features](https://github.com/N3v1/To-Do-App#features)
4. [Installation](https://github.com/N3v1/To-Do-App#installation)
5. [Technical Details](https://github.com/N3v1/To-Do-App#technical-details)
   - [Technologies](https://github.com/N3v1/To-Do-App#technologies)
   - [How to use this App](https://github.com/N3v1/To-Do-App#how-to-use-this-app)
   - [Contributing](https://github.com/N3v1/To-Do-App#contributing)
   - [License](https://github.com/N3v1/To-Do-App#license)
   - [Known issues](https://github.com/N3v1/To-Do-App#known-issues)
```
3. The file should be organized with headings. It should include a few screenshots from the app

If you have any questions, let me know 🙂. 
Thank you in advance 🙏

**Comment by allicht** [comment]
I am interested in helping you rewrite this. Is this app also available on the app store or only on Mac OS? It looks like only on Mac OS right now, but the picture of the iPhone in the instructions makes me second-guess that. Is that what it looks like when you use it on Mac - an iPhone UI window?

**Comment by N3v1** [comment]
Hi @allicht,
no, this app is only for iOS, but I plan to develop a macOS version. The app is not on the app store. 

Sure, I would appreciate it if you rewrite the How-To-Use.md file.

**Comment by allicht** [comment]
I got busy at work, but I will look at this shortly.

**Comment by allicht** [comment]
Okay. The instructions seem to be for setting up the development environment and running the app on a macOS computer rather than directly on an iOS device. Is that correct? Is this read more for developers than users?

**Comment by N3v1** [comment]
> Okay. The instructions seem to be for setting up the development environment and running the app on a macOS computer rather than directly on an iOS device; that is why I asked. Is this read me more for developers than users?

For both
